spring.application.name=account-service
server.port=8081

spring.config.import=optional:configserver:

# spring boot actuator
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=account-service
info.app.description=Service responsible for managing digital wallet accounts and user financial data
info.app.version=1.0.0

# spring cloud config-server
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.serviceId=config-server

# Eureka
eureka.instance.hostname=account-service
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Database
spring.datasource.url=jdbc:mysql://mysql:3306/wallet
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true